config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :vans do
    resources :bookings, only: [ :new, :create, :destroy]
      member do
      patch :decline
      patch :accept
    end
  end
  get 'dashboard', to: 'profils#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :van

  validates :starting_date, :ending_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :vans
  has_many :bookings

  validates :first_name, :last_name, :first_name, :user_city, :birth_date, presence: true
  #:last_name, :birth_date, :email, :user_city, presence: true
  validates :email, uniqueness: true
end

app/models/van.rb
class Van < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_global,
    against: [:model, :van_city, :capacity],
    using: {
      tsearch: { prefix: true }
    }

  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :name, :model, :capacity, :van_city, :price_per_day, presence: true
  geocoded_by :van_city
  after_validation :geocode, if: :will_save_change_to_van_city?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  protected
    def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :user_city, :birth_date])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :user_city, :birth_date])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @van = Van.find(params[:van_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @van = Van.find(params[:van_id])
    @user = current_user
    @booking.van = @van
    @booking.user = @user
    if @booking.save
      @booking.status = "pending"
      @booking.save
      @van.availability = false

      @van.save!
      redirect_to dashboard_path

    else
      render :new
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = "accepted"
    @booking.save
    redirect_to dashboard_path # quand j'aurai la view rediriger au profil
  end

  def decline
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = "declined"
    @booking.save
    redirect_to dashboard_path
  end

  def destroy
    @van = Van.find(params[:van_id])
    @booking = Booking.find_by(van_id: @van, user_id: current_user)
    authorize @booking
    @booking.destroy
    redirect_to vans_path
  end

  private

  def booking_params
    params.require(:booking).permit(:starting_date, :ending_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController
  def dashboard
    # recup les vans du user actuel
    @vans_user = policy_scope(Van).where(user_id: current_user)
    authorize @vans_user
    vans_id = []
    @vans_user.each do |van_user|
      vans_id << van_user.id
    end
    # recup les bookings demande sur les vans precedents
    @bookings_user = policy_scope(Booking).where(van_id: vans_id)
    authorize @bookings_user
    # recup les bookings que l'utilisateur actuel a cree
    @my_bookings = Booking.where(user_id: current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/vans_controller.rb
class VansController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    query = { model: params[:model], capacity: params[:capacity], van_city: params[:van_city] }
    if query.values.all? { |element| element == "" }
      @vans = Van.all
    else
      @vans = Van.search_global("#{params[:model]} #{params[:capacity]} #{params[:van_city]}")
    end
    policy_scope(Van)
    @markers = @vans.geocoded.map do |van|
      {
        lat: van.latitude,
        lng: van.longitude,
        info_window: render_to_string(partial: "info_window", locals: { van: van }),
         #<i class="fas fa-shuttle-van" style="color:#d98526"></i>
      }
    end
  end

  def show
    @van = Van.find(params[:id])
    authorize @van
    @booking = Booking.find_by(user_id: current_user, van_id: @van)
    # will return nil if do not meet any record corresponding to my current_user & van_id, so not my booking
  end

  def new
    @van = Van.new
    authorize @van
  end

  def create
    @van = Van.new(params_van)
    authorize @van
    @van.user = current_user
    if @van.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    @van = Van.find(params[:id])
    authorize @van
  end

  def update
    @van = Van.find(params[:id])
    authorize @van
    @van.update(params_van)
    redirect_to van_path(@van)
  end

  def destroy
    @van = Van.find(params[:id])
    authorize @van
    @van.destroy
    redirect_to dashboard_path
  end

  private

  def params_van
    params.require(:van).permit(:name, :model, :capacity, :van_city, :price_per_day)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<a href="#" onclick="history.go(-1)"  class="btn btn-success mt-5 ml-5"> << Go back to results </a>

<h1 id="van-list">Reservation Details</h1>

<div class="d-flex justify-content-center">
    <div class="card-van">
      <%= image_tag("https://source.unsplash.com/collection/1729942/?sig=#{@van.id}") %>
      <div class="card-van-infos">
        <div>
          <h2><%=@van.name %></h2>
          <p><strong>Model: </strong><%= @van.model %></p>
          <p><strong>Capacity: </strong><%= @van.capacity %></p>
          <p><strong>City: </strong><%= @van.van_city %></p>
          <p><% if @van.availability? == true %>
              <p class="van-status__available">Available</p>
            <% else %>
              <p class="van-status__unavailable">Unavailable</p>
            <% end %>
          </p>
        </div>
        <h2 class="card-van-pricing"><%= @van.price_per_day %>€ /day</h2>
        <%= image_tag "https://source.unsplash.com/collection/4389261/?sig=#{@van.user.id}", class:'card-van-user avatar-bordered' %>
        <!-- <img src="https://images.unsplash.com/photo-1586297135537-94bc9ba060aa?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80" class="card-van-user avatar-bordered" /> -->
      </div>
    </div>
</div>


<div class="container text-secondary mt-5 mb-5">
  <%= simple_form_for [@van, @booking] do |f|%>
    <%= f.input :starting_date %>
    <%= f.input :ending_date %>
    <%= f.submit "Demarre ton vaaan", class: "btn btn-primary", id: "submit-booking", hidden: true %>
  <% end %>
  <button id="booking-confirmation" class="btn btn-primary mt-5">Demarre ton vaaan !</button>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VAN The Road</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <div class="layout">
      <%= render 'shared/navbar' %>
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>

  </body>

</html>

app/views/pages/_search_form.html.erb
<div id="search-form" class="bg-light p-4 shadow-sm rounded">
  <%= form_tag vans_path, method: :get do %>
  <div class="row">
   <div class="col">
     <%= text_field_tag :model,
        params[:model],
        class: "form-control",
        placeholder: "Model"
      %>
   </div>

   <div class="col">
    <%= text_field_tag :van_city,
        params[:van_city],
        class: "form-control",
        placeholder: "City"
      %>
   </div>

   <div class="col">
    <div class="input-group flex-nowrap">
    <span class="input-group-text" id="addon-wrapping"><i class="fas fa-male"></i></span>
      <%= number_field_tag :capacity,
        params[:capacity],
        class: "form-control",
        placeholder: "Capacity",
        min:0
      %>
   </div>
   </div>

   <div class="col">
      <%= submit_tag "Search", class: "btn btn-primary btn-lg" %>
    </div>
  </div>
  <% end %>
</div>

app/views/pages/_van_animation.html.erb
  <div class="translate-animation">
    <i class="fas fa-shuttle-van fa-4x" style="color:#d98526"></i>
  </div>

app/views/pages/home.html.erb
<div class="full-screen" id="home-background">
  <div class="container flex-column d-flex justify-content-center align-items-center">
    <h1 class="text-center mb-5" style="color:white">Van the road with us !</h1>
    <%= render 'van_animation' %>
    <%= render 'search_form' %>
    <div class="title-home">
      <% if policy(Van).create? %>
      <br>
      <br>
      <h1 class="text-center" style="color:white">Or </h1>
      <%= link_to 'Post your van for rent', new_van_path, class: 'btn btn-primary btn-detail' %>
      <% end %>
    </div>
  </div>
</div>

app/views/profils/dashboard.html.erb
<div class="cards-profile">
  <div class="cards-myvans">
    <h2>My vans</h2>
    <% @vans_user.each do |van_user| %>
      <div class="card-profile">
        <img src="https://images.unsplash.com/photo-1561361513-2d000a50f0dc?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2255&q=80" />
        <div class="card-profile-infos">
          <h2><%= van_user.name %></h2>
          <p><strong>Model: </strong><%= van_user.model %></p>
          <p><strong>Capacity: </strong><%= van_user.capacity %></p>
          <p><strong>City: </strong><%= van_user.van_city %></p>
          <% unless van_user.bookings.first.nil? %>
            <p><strong>Starting date: </strong><%= van_user.bookings.last.starting_date %></p>
            <p><strong>Ending date: </strong><%= van_user.bookings.last.ending_date %></p>
          <% end %>
          <p><% if van_user.availability? %>
              <p class="van-status__available">Available</p>
            <% else %>
              <p class="van-status__unavailable">Unavailable</p>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  </div>

  <div class="cards-mybookings">
    <h2>My bookings</h2>
    <% @my_bookings.each do |my_booking| %>
      <div class="card-profile">
        <img src="https://images.unsplash.com/photo-1561361513-2d000a50f0dc?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2255&q=80" />
        <div class="card-profile-infos">
          <h2><%= my_booking.van.name %></h2>
          <p><strong>Starting date: </strong><%= my_booking.starting_date %></p>
          <p><strong>Ending date: </strong><%= my_booking.ending_date %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/Gaudou/VAN_THE_ROAD" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/molki_supreme/" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/lewagonfrance/" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/lewagonlille?lang=fr" target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/school/le-wagon/?originalSubdomain=fr" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart" style="color:#EFE2D7"></i> at Van The Road
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/">
    <i class="fas fa-shuttle-van" style="color:#d98526"></i>
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', '/', class: 'nav-link' %>

      </li>
      <li class="nav-item dropdown">
        <% if user_signed_in? %>
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1400&q=80" />
        <% else %>
        <%= link_to 'Log-In', user_session_path, class: 'btn btn-primary'%>
        <% end %>


        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to 'My Profile', '/dashboard', class: 'dropdown-item' %>
          <%= link_to 'Log out', destroy_user_session_path, :method => :delete, class: 'dropdown-item' %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/vans/_form.html.erb
<%= simple_form_for(@van) do |f|%>
  <%= f.input :name %>
  <%= f.input :model %>
  <%= f.input :capacity, as: :numeric, input_html: { min: '0', step: 'any' } %>
  <%= f.input :van_city %>
  <%= f.input :price_per_day, as: :numeric, input_html: { min: '0', step: 'any' } %>
  <%= f.submit class: "btn btn-primary w-100"%>
<% end %>
</end>

app/views/vans/_info_window.html.erb
<h2><%= van.name %></h2>
<p><%= van.van_city %></p>

app/views/vans/edit.html.erb
<a href="#" onclick="history.go(-1)"  class="btn btn-success mt-5 ml-5"> << Go back to results </a>

<div class="full-screen">
  <div class="container mt-5 text-secondary d-flex justify-content-center align-items-center">
    <div class="col" style="max-width: 500px;">
    <h1>Change your van informations</h1>
    <%= render "form", van: @van %>
    </div>
  </div>
</div>

app/views/vans/index.html.erb
<h1 id="van-list">Choose your van !</h1>
  <div class=" d-flex">

    <div class="cards">
      <% @vans.each do |van| %>
        <div class="card-van">
          <%= image_tag("https://source.unsplash.com/collection/1729942/?sig=#{van.id}") %>
          <div class="card-van-infos">
            <div>
              <h2><%= link_to van.name, van_path(van)%></h2>
              <p><strong>Model: </strong><%= van.model %></p>
              <p><strong>Capacity: </strong><%= van.capacity %></p>
              <p><strong>City: </strong><%= van.van_city %></p>
              <p><% if van.availability? == true %>
              <p class="van-status__available">Available</p>
                <% else %>
                <p class="van-status__unavailable">Unavailable</p>
                <% end %>
                 </p>
            </div>
            <h2 class="card-van-pricing"><%= van.price_per_day %>€ /day</h2>
            <%= image_tag "https://source.unsplash.com/collection/4389261/?sig=#{van.user.id}", class:'card-van-user avatar-bordered' %>
          <!-- <img src="https://images.unsplash.com/photo-1586297135537-94bc9ba060aa?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80" class="card-van-user avatar-bordered" /> -->
            </div>
          </div>
      <% end %>
    </div>
    <div id="map"
       style="width: 100%; height: 100vh;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
  </div>

app/views/vans/new.html.erb
<div class="full-screen">
  <div class="container mt-5 text-secondary d-flex justify-content-center align-items-center">
    <div class="col" style="max-width: 500px;">
    <h2 class="mb-3">Add your van for rent</h2>
    <%= render "form", van: @van %>
    </div>
  </div>
</div>

app/views/vans/show.html.erb
<a href="#" onclick="history.go(-1)"  class="btn btn-success mt-5 ml-5"> << Go back to results </a>

<h1 id="van-list"><br> <strong>Your Choice :</strong> <%=@van.name %> </h1>

<div class="d-flex justify-content-center">

  <div class="card-van">
      <%= image_tag("https://source.unsplash.com/collection/1729942/?sig=#{@van.id}") %>
      <div class="card-van-infos">
        <div>
          <h2><%=@van.name %></h2>
          <p><strong>Model: </strong><%= @van.model %></p>
          <p><strong>Capacity: </strong><%= @van.capacity %></p>
          <p><strong>City: </strong><%= @van.van_city %></p>
          <p><% if @van.availability? == true %>
              <p class="van-status__available">Available</p>
            <% else %>
              <p class="van-status__unavailable">Unavailable</p>
            <% end %>
          </p>
        </div>
        <h2 class="card-van-pricing"><%= @van.price_per_day %>€ /day</h2>
        <%= image_tag "https://source.unsplash.com/collection/4389261/?sig=#{@van.user.id}", class:'card-van-user avatar-bordered' %>
        <!-- <img src="https://images.unsplash.com/photo-1586297135537-94bc9ba060aa?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80" class="card-van-user avatar-bordered" /> -->
      </div>
    </div>
</div>

<div class="d-flex justify-content-center">
  <%= link_to 'Booking', new_van_booking_path(@van), class:'btn btn-info' %>
</div>

<br>


  <% if @van.user == current_user %>
  <div class="card-van p-4 mx-auto">
    <h4 id="van-list" class="text-secondary"> <strong><i class="fas fa-arrow-down"></i> It's your van <i class="fas fa-arrow-down"></i></strong></h4>
    <br>
  <% end %>

  <div class="d-flex justify-content-center">
    <% if policy(@van).edit? %>
      <%= link_to 'Edit my Van', edit_van_path(@van), class: 'btn btn-secondary mr-5' %>
    <% end %>

    <% if policy(@van).destroy? %>
      <%= link_to '- Delete my Van', van_path(@van), method: :delete, class:'btn btn-danger', id:"delete-van-btn", hidden: true%>
        <button id="delete-van-confirmation" class="btn btn-danger">Delete my van</button>
    <% end %>
  </div>
</div>